package com.seolytics.domain;

public enum IssueType {
    MISSING_TITLE,
    EMPTY_TITLE,
    DUPLICATE_TITLE,
    MISSING_META_DESCRIPTION,
    DUPLICATE_META_DESCRIPTION,
    BROKEN_INTERNAL_LINK,
    BROKEN_EXTERNAL_LINK,
    HTTP_CLIENT_ERROR,
    HTTP_SERVER_ERROR,
    REDIRECT_CHAIN,
    MISSING_IMAGE_ALT,
    MISSING_CANONICAL,
    MISSING_H1,
    MULTIPLE_H1,
    MISSING_VIEWPORT,
    INSECURE_HTTP,
    MISSING_SITEMAP,
    INVALID_SITEMAP,
    ROBOTS_TXT_INACCESSIBLE,
    GA4_TAG_NOT_DETECTED
}
